Fixed Conflict error uploading old artifacts
Given a workflow that has had multiple runs (retrys) that uploaded an artifact. These older artifacts will now be skipped/filtered out and used the latest version.

This fixes conflict error when uploading two artifacts with the same name.
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run